[package]
name = "day05"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = {version = "0.17.7", features = ["rayon"] }
indoc = "2.0.4"
itertools = "0.12.0"
nom = "7.1.3"
nom-supreme = "0.8.0"
rayon = "1.8.0"
